### ISSUE TITLE
Don't you want to do the same thing with Praat?

### ISSUE THREAD

**Issue by agricolamz** [borstell/ELAN_annotation_duration#1]
If you transform your .eaf file to .TextGrid, using Praat script you can even get the total duration of each segment. But may be I poke my nose to deep into your business. Sorry if you've already knew.

**Comment by borstell** [comment]
Thanks! Yes, there are plenty of ways to get the get the total duration of the individual annotation segments, data that are in the eaf-files already. The purpose of this script is just to see how much data have been gone through, in case one only annotates few cells in longer stretches of video/audio data. Of course, summing up the duration of the files as well is another option.
